### PR TITLE
Support for local device info

### LINKED ISSUE #17: Support for local device info
Local devices does not have the `/clients/list` we need a better way to return info about the client than `get_clients()` when connected via `LocalAPISession`. Can the code used for/in discovery (netdisco) be used?

Home-Assistant expect the following:

- ip
- id (could preferrable be mac-address)
- name
- version

### PR DESCRIPTION
**Pull request by fredrike**
fixes #17

### CODE REVIEW

**Comment by molobrakos** [comment]
The code is netdisco is going to be removed anyway so Home Assistant needs some other way (than netdisco) of discovering local devices I guess. This code is also currently duplicated here: https://github.com/molobrakos/tellsticknet/blob/master/tellsticknet/discovery.py#L80 (already rewritten to being async). Maybe we should try to merge it somehow in the future. I don't know if you plan to rewrite this library to async in the near future or instead create your own from scratch maybe?

**Comment by fredrike** [comment]
> The code is netdisco is going to be removed anyway so Home Assistant needs some other way (than netdisco) of discovering local devices I guess. This code is also currently duplicated here: https://github.com/molobrakos/tellsticknet/blob/master/tellsticknet/discovery.py#L80 (already rewritten to being async). Maybe we should try to merge it somehow in the future. I don't know if you plan to rewrite this library to async in the near future or instead create your own from scratch maybe?

 * I fully understand the issue with duplicated code but this will be a quite small part that I think could be ok to have in this lib instead of adding extra dependencies.
 * I'm planning to leave tellduslive in favor for mqtt pretty soon but like to get the device-integration finished in hass first.

**Comment by molobrakos** [comment]
Sorry, been travelling for some weeks. Is this pr still alive?

**Comment by fredrike** [comment]
> Sorry, been travelling for some weeks. Is this pr still alive?

Yes, I was hoping it could be merged at the current stage.

**Comment by fredrike** [comment]
Thank you for merge, please let me know when you have had time to upload a new version to pypi.

**Pull request merged**
