### PR TITLE
allow public_key, private_key in initiating session

### PR DESCRIPTION
**Pull request by fredrike**
Please do a version bump too ❤️ ..

### CODE REVIEW

**Comment by molobrakos** [comment]
Ok, is all the HA integration in place?

**Comment by fredrike** [comment]
Almost, I think I have the things I want in place now.

**Comment by molobrakos** [comment]
Excellent work, you rock! I'll make a release later today!

**Comment by molobrakos** [comment]
What about the comment you made inline? (on mobile can't search for it now)

**Comment by molobrakos** [comment]
Referring to this: https://github.com/molobrakos/tellduslive/commit/e0bbac416fd87ca0f3a2c7a510ff6dc146b42ea9#r31582180

**Comment by molobrakos** [comment]
https://github.com/molobrakos/tellduslive/releases/tag/v0.10.8

**Pull request merged**
