### PR TITLE
Adds support for tellstick net communication over UDP

### PR DESCRIPTION
**Pull request by kentsoderlind**
Adds support for tellstick net communication over UDP.
Uses a local config to describe switches and sensors but is capable of auto sensing sensors and switches by listening on local network and creating sensor and switch objects.

This code is useful for controlling old tellstick net devices and intended to be used in home assistant.

### CODE REVIEW

**Comment by molobrakos** [comment]
Can we keep the code that are copied from tellsticknet-lib in the original location (or did you modify it much, I didn't do a diff) and just import it from there instead (I don't mind adding that as a dependency)?

Also, I notice now identical constants are definied in more than one place.

**Comment by kentsoderlind** [comment]
The code is to modified to be checked back to  the tellsticknet-lib.

Ye, I got lazy at the end and made a constants.py for all constants used.

**Comment by kentsoderlind** [comment]
the copied code is removed.
we need to wait for https://github.com/molobrakos/tellsticknet/pull/9 before merging this code to main branch

**Comment by molobrakos** [comment]
See https://github.com/molobrakos/tellduslive/issues/8

**Pull request closed without merging**
